
export default {
    googleAPIKey: 'AIzaSyArvs1JMRu75URu-Efo9MOUxZHC_KJ8YJc',
    WebServerBaseURL: null,
    orderStatus: 0,
    cartsList:[],
    env:'', 
    env1:'',
    vouchersList:[],
     sandboxKey: "AfhqcvtDLrT5AG5wLfEQtX8_JqpNwco7yGp4CK0xMj0KFhOnMI9xpUusGWp4-lJPPJQp7N6Fn2td15RV",
    // sandboxKey: "EIQtJAJycKL-dDm9trucq1Xv8oy_zc_SgvdYeU5IlBIoviTZKgKR6s0uXa2JFiMWKLKQE_7y8JZ7trhc",
    Accept: 'application/json',
    Content: 'application/x-www-form-urlencoded',
    Authorization: '',
    TimeStamp: '',
    editTextBaseColor: "green",
    editTextErrorColor: "red",
    inputBorderColor: "#DDDDDD",
    editTextTintColor: "red",
    colorWhite:"#ffffff",
    colorBlack:"#000000",
    colorinputBorder:"#C6C6C6",
    colorGreyccccc9:"#ccccc9",
    colorMainTheme:"#FC3E3B",
    appBackgroundColor:"#FC3E3B",
    // googleApiKey:'AIzaSyDuFKkvF9g-CWiYDTW2fuTV_1v72mwPfJo',
    FontFamilyRegular: 'Montserrat-Regular',
    FontFamilySemiBold: 'Montserrat-SemiBold',
    FontFamilyMedium: 'Montserrat-SemiBold',
    FontFamilyBold: 'Montserrat-Bold',
    FontFamilyShadow: 'ShadowsIntoLightTwo-Regular',
    FontFamilyLight: 'Montserrat-Regular',
    FontFamilyItalic: 'Montserrat-Italic',
    colorLightGrey: '#F7F6F7',
    colorGrey: '#f3f1f3',
    colorGreyBG: '#606060',
    colorGreyBG2: '#3b3b3b',
    colorBlue: '#2980b6',
    colorNavyBlue: '#419ab1',
    colorGreyBGMain: '#2473A3',
    colorGreyBGInputBox: 'rgba(225,225,225,0.2)',
    currency_symbol: '£',


};
